### ISSUE TITLE
Error at audiofilm.py: ValueError: Unexpectedly found an instance of type `<class 'tensorflow.python.framework.ops.Tensor'>`. Expected a symbolic tensor instance.

### ISSUE THREAD

**Issue by mosem** [kuleshov/audio-super-res#44]
Hi,
I'm getting the following error, and have no idea how to proceed.
Any help would be much appreciated.
Thanks!

```
training...
List of arrays in input file: ['data', 'label']
Shape of X: (3328, 8192, 1)
Shape of Y: (3328, 8192, 1)
List of arrays in input file: ['data', 'label']
Shape of X: (384, 8192, 1)
Shape of Y: (384, 8192, 1)
audiotfilm
building model...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/keras/engine/base_layer.py", line 279, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "/usr/lib/python3/dist-packages/keras/backend/theano_backend.py", line 221, in is_keras_tensor
    str(type(x)) + '`. '
ValueError: Unexpectedly found an instance of type `<class 'tensorflow.python.framework.ops.Tensor'>`. Expected a symbolic tensor instance.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/run.py", line 185, in <module>
    main()
  File "src/run.py", line 182, in main
    args.func(args)
  File "src/run.py", line 128, in train
    model = get_model(args, n_dim, r, from_ckpt=False, train=True)
  File "src/run.py", line 166, in get_model
    strides=args.strides, opt_params=opt_params, log_prefix=args.logname)
  File "/cs/labs/adiyoss/moshemandel/audio-super-res-2/src/models/audiotfilm.py", line 31, in __init__
    opt_params=opt_params, log_prefix=log_prefix)
  File "/cs/labs/adiyoss/moshemandel/audio-super-res-2/src/models/model.py", line 48, in __init__
    self.predictions = self.create_model(n_dim, r)
  File "/cs/labs/adiyoss/moshemandel/audio-super-res-2/src/models/audiotfilm.py", line 89, in create_model
    activation=None, padding='same', kernel_initializer=Orthogonal()))(x)
  File "/usr/lib/python3/dist-packages/keras/engine/base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "/usr/lib/python3/dist-packages/keras/engine/base_layer.py", line 285, in assert_input_compatibility
    str(inputs) + '. All inputs to the layer '
ValueError: Layer conv1d_1 was called with an input that isn't a symbolic tensor. Received type: <class 'tensorflow.python.framework.ops.Tensor'>. Full input: [<tf.Tensor 'X:0' shape=(None, None, 1) dtype=float32>]. All inputs to the layer should be tensors.
```

**Comment by Sawyerb** [comment]
What command are you running to kick off training? And what version of TensorFlow and Keras are you using?

**Comment by mosem** [comment]
Hi,
This is the command:
```
python src/run.py train \
  --train ./data/vctk/speaker1/8-16/0.5-0.5/vctk-speaker1-train.2.16000.8192.4096.h5 \
  --val ./data/vctk/speaker1/8-16/0.5-0.5/vctk-speaker1-val.2.16000.8192.4096.h5 \
  -e 1 \
  --batch-size 64 \
  --lr 3e-4 \
  --logname singlespeaker \
  --model audiotfilm \
  --r 2 \
  --layers 4 \
  --piano false \
  --pool_size 2 \
  --strides 2 \
  --full true
```

And I'm using tensorflow==2.4.1 and keras==2.4.0.
(with Cuda/11.0 and cudnn/8.02)

Thanks!

**Comment by Sawyerb** [comment]
Hmm, that looks correct. What version of python are you using?

**Comment by mosem** [comment]
Python 3.7.3

**Comment by mosem** [comment]
OK, false alarm.
I found the problem - my keras version was not the right one (I thought it was 2.4.0 but it wasn't).

Thank you for your time!

**Comment by Sawyerb** [comment]
Awesome, great!
