### ISSUE TITLE
./singlespeaker.lr0.000300.1.g4.b64.meta does not exist.

### ISSUE THREAD

**Issue by FurkanGozukara** [kuleshov/audio-super-res#57]
I have successfully installed

downloaded pre trained model and extracted into the src folder like below

![image](https://user-images.githubusercontent.com/19240467/219139627-a2c31c63-254b-4204-8e18-97829f350d9d.png)

running this command

python run.py eval --logname ./singlespeaker.lr0.000300.1.g4.b64 --out-label singlespeaker-out --wav-file-list list.txt --r 4 --pool_size 2 --strides 2 --model audiotfilm

here full logs

```
(audio-super-res) C:\audio super res\src>python run.py eval --logname ./singlespeaker.lr0.000300.1.g4.b64 --out-label singlespeaker-out --wav-file-list list.txt --r 4 --pool_size 2 --strides 2 --model audiotfilm
2023-02-15 22:59:17.350890: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-02-15 22:59:17.351062: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
audiotfilm
2023-02-15 22:59:20.811747: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-02-15 22:59:20.812488: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2023-02-15 22:59:20.826132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.777GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2023-02-15 22:59:20.827827: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-02-15 22:59:20.829273: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2023-02-15 22:59:20.830615: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2023-02-15 22:59:20.836817: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2023-02-15 22:59:20.838811: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2023-02-15 22:59:20.847516: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2023-02-15 22:59:20.849067: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2023-02-15 22:59:20.850036: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2023-02-15 22:59:20.850899: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-02-15 22:59:20.851740: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-15 22:59:20.892047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-02-15 22:59:20.892146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]
2023-02-15 22:59:20.892631: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "run.py", line 176, in <module>
    main()
  File "run.py", line 173, in main
    args.func(args)
  File "run.py", line 130, in eval
    model.load(args.logname) # from default checkpoint
  File "C:\audio super res\src\models\model.py", line 178, in load
    self.saver = tf.compat.v1.train.import_meta_graph(meta)
  File "C:\Users\King\.conda\envs\audio-super-res\lib\site-packages\tensorflow\python\training\saver.py", line 1461, in import_meta_graph
    **kwargs)[0]
  File "C:\Users\King\.conda\envs\audio-super-res\lib\site-packages\tensorflow\python\training\saver.py", line 1475, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "C:\Users\King\.conda\envs\audio-super-res\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 630, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
OSError: File ./singlespeaker.lr0.000300.1.g4.b64.meta does not exist.
```

**Comment by FurkanGozukara** [comment]
here the installation logs no errors
```

(base) C:\audio super res>conda env create -f environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.1.0

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: / "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

| "By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA - https://docs.nvidia.com/deeplearning/cudnn/sla/index.html"

done
Installing pip dependencies: - Ran pip subprocess with arguments:
['C:\\Users\\King\\.conda\\envs\\audio-super-res\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\audio super res\\condaenv.g3opewu9.requirements.txt']
Pip subprocess output:
Collecting tensorflow==2.4.1
  Downloading tensorflow-2.4.1-cp37-cp37m-win_amd64.whl (370.7 MB)
     -------------------------------------- 370.7/370.7 MB 1.9 MB/s eta 0:00:00
Collecting keras==2.4.0
  Downloading Keras-2.4.0-py2.py3-none-any.whl (170 kB)
     ---------------------------------------- 170.2/170.2 kB ? eta 0:00:00
Collecting numpy==1.19.5
  Downloading numpy-1.19.5-cp37-cp37m-win_amd64.whl (13.2 MB)
     --------------------------------------- 13.2/13.2 MB 11.3 MB/s eta 0:00:00
Collecting scipy==1.6.0
  Downloading scipy-1.6.0-cp37-cp37m-win_amd64.whl (32.5 MB)
     ---------------------------------------- 32.5/32.5 MB 1.3 MB/s eta 0:00:00
Collecting librosa==0.8.1
  Using cached librosa-0.8.1-py3-none-any.whl (203 kB)
Collecting h5py==2.10.0
  Downloading h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 231.5 kB/s eta 0:00:00
Collecting matplotlib==3.3.4
  Downloading matplotlib-3.3.4-cp37-cp37m-win_amd64.whl (8.5 MB)
     ---------------------------------------- 8.5/8.5 MB 11.3 MB/s eta 0:00:00
Collecting tqdm==4.58.0
  Downloading tqdm-4.58.0-py2.py3-none-any.whl (73 kB)
     ---------------------------------------- 73.2/73.2 kB ? eta 0:00:00
Collecting typing-extensions~=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting gast==0.3.3
  Downloading gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting tensorboard~=2.4
  Using cached tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
Collecting grpcio~=1.32.0
  Downloading grpcio-1.32.0-cp37-cp37m-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 11.5 MB/s eta 0:00:00
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers~=1.12.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting tensorflow-estimator<2.5.0,>=2.4.0
  Downloading tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
     -------------------------------------- 462.0/462.0 kB 9.8 MB/s eta 0:00:00
Collecting keras-preprocessing~=1.1.2
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     ---------------------------------------- 42.6/42.6 kB ? eta 0:00:00
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting protobuf>=3.9.2
  Downloading protobuf-4.21.12-cp37-cp37m-win_amd64.whl (526 kB)
     ------------------------------------- 526.5/526.5 kB 11.0 MB/s eta 0:00:00
Collecting six~=1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting termcolor~=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: wheel~=0.35 in c:\users\king\.conda\envs\audio-super-res\lib\site-packages (from tensorflow==2.4.1->-r C:\audio super res\condaenv.g3opewu9.requirements.txt (line 1)) (0.38.4)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\king\appdata\roaming\python\python37\site-packages (from tensorflow==2.4.1->-r C:\audio super res\condaenv.g3opewu9.requirements.txt (line 1)) (1.12.1)
Collecting absl-py~=0.10
  Downloading absl_py-0.15.0-py3-none-any.whl (132 kB)
     -------------------------------------- 132.0/132.0 kB 7.6 MB/s eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0-cp37-cp37m-win_amd64.whl (153 kB)
     ---------------------------------------- 153.2/153.2 kB ? eta 0:00:00
Collecting audioread>=2.0.0
  Using cached audioread-3.0.0.tar.gz (377 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting packaging>=20.0
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting scikit-learn!=0.19.0,>=0.14.0
  Downloading scikit_learn-1.0.2-cp37-cp37m-win_amd64.whl (7.1 MB)
     ---------------------------------------- 7.1/7.1 MB 11.4 MB/s eta 0:00:00
Collecting soundfile>=0.10.2
  Downloading soundfile-0.12.1-py2.py3-none-win_amd64.whl (1.0 MB)
     ---------------------------------------- 1.0/1.0 MB 12.8 MB/s eta 0:00:00
Collecting resampy>=0.2.2
  Using cached resampy-0.4.2-py3-none-any.whl (3.1 MB)
Collecting numba>=0.43.0
  Downloading numba-0.56.4-cp37-cp37m-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 11.3 MB/s eta 0:00:00
Collecting pooch>=1.0
  Using cached pooch-1.6.0-py3-none-any.whl (56 kB)
Collecting joblib>=0.14
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting decorator>=3.0.0
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-9.4.0-cp37-cp37m-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 10.6 MB/s eta 0:00:00
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp37-cp37m-win_amd64.whl (54 kB)
     ---------------------------------------- 54.9/54.9 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: setuptools in c:\users\king\.conda\envs\audio-super-res\lib\site-packages (from numba>=0.43.0->librosa==0.8.1->-r C:\audio super res\condaenv.g3opewu9.requirements.txt (line 5)) (67.3.1)
Collecting importlib-metadata
  Using cached importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Collecting llvmlite<0.40,>=0.39.0dev0
  Downloading llvmlite-0.39.1-cp37-cp37m-win_amd64.whl (23.2 MB)
     --------------------------------------- 23.2/23.2 MB 11.1 MB/s eta 0:00:00
Collecting requests>=2.19.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting appdirs>=1.3.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting cffi>=1.0
  Downloading cffi-1.15.1-cp37-cp37m-win_amd64.whl (179 kB)
     ---------------------------------------- 179.3/179.3 kB ? eta 0:00:00
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.16.0-py2.py3-none-any.whl (177 kB)
Collecting werkzeug>=1.0.1
  Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
     ------------------------------------- 233.6/233.6 kB 14.0 MB/s eta 0:00:00
Collecting protobuf>=3.9.2
  Downloading protobuf-3.20.3-cp37-cp37m-win_amd64.whl (905 kB)
     ------------------------------------- 905.1/905.1 kB 11.5 MB/s eta 0:00:00
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting zipp>=0.5
  Using cached zipp-3.13.0-py3-none-any.whl (6.7 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.0.1-cp37-cp37m-win_amd64.whl (94 kB)
     ---------------------------------------- 94.0/94.0 kB ? eta 0:00:00
Collecting MarkupSafe>=2.1.1
  Downloading MarkupSafe-2.1.2-cp37-cp37m-win_amd64.whl (16 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Building wheels for collected packages: audioread, termcolor
  Building wheel for audioread (setup.py): started
  Building wheel for audioread (setup.py): finished with status 'done'
  Created wheel for audioread: filename=audioread-3.0.0-py3-none-any.whl size=23736 sha256=c49587967fe34ecc72bb7d7b423f912b4db3ca9a96f43d9b0a7a00d4434cc982
  Stored in directory: c:\users\king\appdata\local\pip\cache\wheels\71\a4\fa\24175dada88ca37d7fd22ffec10b33cb0a4909d7d07f04101f
  Building wheel for termcolor (setup.py): started
  Building wheel for termcolor (setup.py): finished with status 'done'
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4855 sha256=feb02d834cba92cffd3c20b3f165b08e932654e5ec261289431ebf0fd843544d
  Stored in directory: c:\users\king\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
Successfully built audioread termcolor
Installing collected packages: typing-extensions, termcolor, tensorflow-estimator, tensorboard-plugin-wit, pyasn1, flatbuffers, charset-normalizer, appdirs, zipp, urllib3, tqdm, threadpoolctl, tensorboard-data-server, six, rsa, pyyaml, pyparsing, pycparser, pyasn1-modules, protobuf, pillow, packaging, oauthlib, numpy, MarkupSafe, llvmlite, kiwisolver, joblib, idna, gast, decorator, cycler, certifi, cachetools, audioread, werkzeug, scipy, requests, python-dateutil, opt-einsum, keras-preprocessing, importlib-metadata, h5py, grpcio, google-pasta, google-auth, cffi, astunparse, absl-py, soundfile, scikit-learn, requests-oauthlib, pooch, numba, matplotlib, markdown, resampy, google-auth-oauthlib, tensorboard, librosa, tensorflow, keras
Successfully installed MarkupSafe-2.1.2 absl-py-0.15.0 appdirs-1.4.4 astunparse-1.6.3 audioread-3.0.0 cachetools-5.3.0 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.0.1 cycler-0.11.0 decorator-5.1.1 flatbuffers-1.12 gast-0.3.3 google-auth-2.16.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.32.0 h5py-2.10.0 idna-3.4 importlib-metadata-6.0.0 joblib-1.2.0 keras-2.4.0 keras-preprocessing-1.1.2 kiwisolver-1.4.4 librosa-0.8.1 llvmlite-0.39.1 markdown-3.4.1 matplotlib-3.3.4 numba-0.56.4 numpy-1.19.5 oauthlib-3.2.2 opt-einsum-3.3.0 packaging-23.0 pillow-9.4.0 pooch-1.6.0 protobuf-3.20.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pyparsing-3.0.9 python-dateutil-2.8.2 pyyaml-6.0 requests-2.28.2 requests-oauthlib-1.3.1 resampy-0.4.2 rsa-4.9 scikit-learn-1.0.2 scipy-1.6.0 six-1.15.0 soundfile-0.12.1 tensorboard-2.11.2 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.4.1 tensorflow-estimator-2.4.0 termcolor-1.1.0 threadpoolctl-3.1.0 tqdm-4.58.0 typing-extensions-3.7.4.3 urllib3-1.26.14 werkzeug-2.2.3 zipp-3.13.0

done
#
# To activate this environment, use
#
#     $ conda activate audio-super-res
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
```

**Comment by FurkanGozukara** [comment]
@kuleshov @WMRamadan @Sawyerb @jimmsta @Lootwig 

any help is very much appreciated

**Comment by WMRamadan** [comment]
@FurkanGozukara Interesting I have not tried this on Windows, can you clarify which version of Windows this is? (Windows 10 or 11 - Pro or Home)

Did you check that `singlespeaker.lr0.000300.1.g4.b64.meta` exists and that you have followed the instructions on how to train the model?

Can you show how you trained the model?

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara Interesting I have not tried this on Windows, can you clarify which version of Windows this is? (Windows 10 or 11 - Pro or Home)
> 
> Did you check that `singlespeaker.lr0.000300.1.g4.b64.meta` exists and that you have followed the instructions on how to train the model?
> 
> Can you show how you trained the model?

i didnt train any model. i have downloaded the model file you shared. the pre trained one. 

extracted like this into the src

![image](https://user-images.githubusercontent.com/19240467/219330862-88c46419-9999-4ef0-afdc-93fc00314f36.png)

then i did run this command

`python run.py eval --logname ./singlespeaker.lr0.000300.1.g4.b64 --out-label singlespeaker-out --wav-file-list list.txt --r 4 --pool_size 2 --strides 2 --model audiotfilm`

I am using Windows 10 pro

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045

@WMRamadan

**Comment by WMRamadan** [comment]
@FurkanGozukara That model was trained using a batch size of 16. Use the following:

```
python run.py eval   --logname ./singlespeaker.lr0.000300.1.g4.b16   --out-label singlespeaker-out   --wav-file-list ../data/vctk/speaker1/speaker1-val-files.txt   --r 4   --pool_size 2   --strides 2   --model audiotfilm
```

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara That model was trained using a batch size of 16. Use the following:
> 
> ```
> python run.py eval   --logname ./singlespeaker.lr0.000300.1.g4.b16   --out-label singlespeaker-out   --wav-file-list ../data/vctk/speaker1/speaker1-val-files.txt   --r 4   --pool_size 2   --strides 2   --model audiotfilm
> ```

thank you so much

started processing but via CPU not using GPU due to below errors. I have RTX 3060 and installed exactly as following the instructions. during installation 0 error as I have show above messages

processing not ended yet so cant comment on it. also it is hard coded looking for this folder for data to be in

`\data\vctk\VCTK-Corpus\wav48\p225`

```
(audio-super-res) C:\audio super res\src>python run.py eval   --logname ./singlespeaker.lr0.000300.1.g4.b16   --out-label singlespeaker-out   --wav-file-list list.txt   --r 4   --pool_size 2   --strides 2   --model audiotfilm
2023-02-16 13:14:18.942358: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-02-16 13:14:18.942472: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
audiotfilm
2023-02-16 13:14:21.400084: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-02-16 13:14:21.400818: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2023-02-16 13:14:21.417991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.777GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2023-02-16 13:14:21.419569: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-02-16 13:14:21.420944: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2023-02-16 13:14:21.422254: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2023-02-16 13:14:21.425587: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2023-02-16 13:14:21.426690: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2023-02-16 13:14:21.430739: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2023-02-16 13:14:21.432268: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2023-02-16 13:14:21.433068: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2023-02-16 13:14:21.433137: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-02-16 13:14:21.433786: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-16 13:14:21.470877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-02-16 13:14:21.470998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]
2023-02-16 13:14:21.471057: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-02-16 13:14:22.490435: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
5.mp3

```

**Comment by WMRamadan** [comment]
@FurkanGozukara I don't think you are following the instructions correctly.

Did you do the following step: https://github.com/kuleshov/audio-super-res#retrieving-data

Also did you install CUDA Toolkit on your machine? (https://developer.nvidia.com/cuda-toolkit-archive)

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara I don't think you are following the instructions correctly.
> 
> Did you do the following step: https://github.com/kuleshov/audio-super-res#retrieving-data
> 
> Also did you install CUDA Toolkit on your machine? (https://developer.nvidia.com/cuda-toolkit-archive)


I am not doing any training. that sections is about training?

also processing ended

here inputs and outputs

[p225.zip](https://github.com/kuleshov/audio-super-res/files/10754821/p225.zip)

1 by 1 sound files

input : http://sndup.net/f7j8

singlespeaker-out.hr : http://sndup.net/hs5f

no I didnt install cuda. going to install now. you should put that into the description. i am installing latest version

![image](https://user-images.githubusercontent.com/19240467/219338676-00bab72f-7eae-4b23-a960-b65a89d6335f.png)

**Comment by FurkanGozukara** [comment]
could you process this input and give me what output you are getting?

i didn't notice any difference : http://sndup.net/f7j8

perhaps mine not working?

[input mp3.zip](https://github.com/kuleshov/audio-super-res/files/10754869/input.mp3.zip)

@WMRamadan

**Comment by Sawyerb** [comment]
@FurkanGozukara try this:

`python run.py eval   --logname ./singlespeaker.lr0.000300.1.g4.b16/model.ckpt-10401   --out-label singlespeaker-out   --wav-file-list ../data/vctk/speaker1/speaker1-val-files.txt   --r 4   --pool_size 2   --strides 2   --model audiotfilm`

The logname should include the checkpoint that you're using.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara try this:
> 
> `python run.py eval --logname ./singlespeaker.lr0.000300.1.g4.b16/model.ckpt-10401 --out-label singlespeaker-out --wav-file-list ../data/vctk/speaker1/speaker1-val-files.txt --r 4 --pool_size 2 --strides 2 --model audiotfilm`
> 
> The logname should include the checkpoint that you're using.

I don't have ckpt file it is not included in pre trained model. Can you upload it for me?

Or it processes input file list and generates a new ckpt?

I don't want training. I want to give input and get enhanced output

**Comment by Sawyerb** [comment]
I see the checkpoint in the screenshot you posted: 
![image](https://user-images.githubusercontent.com/16441040/219408542-d1bee50a-266f-4664-af69-94437ceadbac.png)

**Comment by satani99** [comment]
Hey @FurkanGozukara How much time did it take to run inference?

**Comment by FurkanGozukara** [comment]
> Hey @FurkanGozukara How much time did it take to run inference?

I can't remember

But I have this tutorial now

https://youtu.be/OiMRlqcgDL0
